"""add_da_recommendations_table

Revision ID: db62da066f3b
Revises: c6f0ca6ec5cb
Create Date: 2025-10-31 13:19:33.935501

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'db62da066f3b'
down_revision = 'c6f0ca6ec5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


